### ISSUE TITLE
MustRegister fails to register vector

### ISSUE THREAD

**Issue by ivanayov** [prometheus/client_golang#671] opened 2019-10-25 10:58 UTC
Based on the documentation [[1]](https://godoc.org/github.com/prometheus/client_golang/prometheus#Gauge) [[2]](v), vectors are of type `Collector` and are registered the same way as Collectors like Gauge, Counter, etc

[Official example of registering GaugeVec](https://github.com/prometheus/client_golang/blob/master/prometheus/examples_test.go#L66)

When I do `prometheus.MustRegister(opsQueued)` where `opsQueued` is of type `Gauge` or `Counter`, it appears in the metrics:
```
$ curl http://localhost:2112/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5257    0  5257    0     0   961k      0 --:--:-- --:--:-- --:--:-- 1026k
# HELP ops_queued Number of blob storage operations waiting to be processed.
# TYPE ops_queued gauge
ops_queued 0
```

When I change to vector type, it's not registered anymore:
```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5135    0  5135    0     0   885k      0 --:--:-- --:--:-- --:--:-- 1002k
```
When I register this way, it's also registered: `prometheus.MustRegister(opsQueued.WithLabelValues("bob"))`:

```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5261    0  5261    0     0   939k      0 --:--:-- --:--:-- --:--:-- 1027k
# HELP ops_queued Number of blob storage operations waiting to be processed.
# TYPE ops_queued gauge
ops_queued{test="bob"} 0

```

Also following the given examples, values are not changed and/or incremented.

Last commit:
```
commit 333f01cef0d61f9ef05ada3d94e00e69c8d5cdda (HEAD -> master, origin/master, origin/HEAD)
Merge: 49d8fa7 06342cf
Author: Björn Rabenstein <beorn@grafana.com>
Date:   Fri Oct 25 01:19:15 2019 +0200

    Merge pull request #668 from kamaev/master
    
    Send Graphite metrics with tags
```

Thanks,
Ivana

**Comment by beorn7** [comment] 2019-10-25 11:16
You must initialize a vector element to make it show up because the vector cannot predict what label values you will have.

The example you linked is doing that correctly. Look at the whole example code: https://github.com/prometheus/client_golang/blob/master/prometheus/examples_test.go#L51-L73

Are you really doing all the things as shown there?

If yes, and if the metric doesn't show up and doesn't get incremented, that would be a really serious bug indeed.

**Comment by ivanayov** [comment] 2019-10-25 14:12
@beorn7 If I copy-paste the example, it doesn't work. If I move `prometheus.MustRegister(opsQueued)` to `init()` method, and [add values](https://github.com/prometheus/client_golang/blob/master/prometheus/examples_test.go#L69-L72) after in another method, `ops_queued` is registered only when it's not a vector. In both cases it's value is not changed.
I'm going to copy-paste code in a new comment. 

Following [this documentation](https://prometheus.io/docs/guides/go-application/), but with `init()` method, that's missing in the example, it's the same: `Counter` is registered only if it's not a vector, and the value keeps to be zero.

**Comment by ivanayov** [comment] 2019-10-25 14:18
Case 1:
```

func ExampleGaugeVec() {
	opsQueued := prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "our_company",
			Subsystem: "blob_storage",
			Name:      "ops_queued",
			Help:      "Number of blob storage operations waiting to be processed, partitioned by user and type.",
		},
		[]string{
			// Which user has requested the operation?
			"user",
			// Of what type is the operation?
			"type",
		},
	)
	prometheus.MustRegister(opsQueued)

	// Increase a value using compact (but order-sensitive!) WithLabelValues().
	opsQueued.WithLabelValues("bob", "put").Add(4)
	// Increase a value with a map using WithLabels. More verbose, but order
	// doesn't matter anymore.
	opsQueued.With(prometheus.Labels{"type": "delete", "user": "alice"}).Inc()
}

func run() {
	http.Handle("/metrics", promhttp.Handler())
	http.ListenAndServe(":9090", nil)
}

func main() {

	run()

	ExampleGaugeVec()
}

Running `go run main.go`

Result:
```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4997    0  4997    0     0   116k      0 --:--:-- --:--:-- --:--:--  119k
```

**Comment by ivanayov** [comment] 2019-10-25 14:21
Case 2: (same, but with Gauge and without `init()`)
```


func ExampleGauge() {
	opsQueued := prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: "our_company",
		Subsystem: "blob_storage",
		Name:      "ops_queued",
		Help:      "Number of blob storage operations waiting to be processed.",
	})
	prometheus.MustRegister(opsQueued)

	// 10 operations queued by the goroutine managing incoming requests.
	opsQueued.Add(10)
	// A worker goroutine has picked up a waiting operation.
	opsQueued.Dec()
	// And once more...
	opsQueued.Dec()
}

func run() {
	http.Handle("/metrics", promhttp.Handler())
	http.ListenAndServe(":9090", nil)
}

func main() {

	run()

	ExampleGauge()
}
```
Running  `go run main.go`

Result:
```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4997    0  4997    0     0   144k      0 --:--:-- --:--:-- --:--:--  147k
```

**Comment by ivanayov** [comment] 2019-10-25 14:27
Case 3: (Gauge with `init()`)

```
var (
	opsQueued = prometheus.NewGauge(prometheus.GaugeOpts{
		Namespace: "our_company",
		Subsystem: "blob_storage",
		Name:      "ops_queued",
		Help:      "Number of blob storage operations waiting to be processed.",
	})
)

func ExampleGauge() {

	// 10 operations queued by the goroutine managing incoming requests.
	opsQueued.Add(10)
	// A worker goroutine has picked up a waiting operation.
	opsQueued.Dec()
	// And once more...
	opsQueued.Dec()
}

func init() {
	prometheus.MustRegister(opsQueued)

}

func run() {
	http.Handle("/metrics", promhttp.Handler())
	http.ListenAndServe(":9090", nil)
}

func main() {

	run()

	ExampleGauge()
}

```
Running `go run main.go`

Result: (keeps `0`)
```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5185    0  5185    0     0   733k      0 --:--:-- --:--:-- --:--:--  843k
# HELP our_company_blob_storage_ops_queued Number of blob storage operations waiting to be processed.
# TYPE our_company_blob_storage_ops_queued gauge
our_company_blob_storage_ops_queued 0

```

**Comment by ivanayov** [comment] 2019-10-25 14:29
Case 4: (GaugeVec with `init()`)

```

var (
	opsQueued = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "our_company",
			Subsystem: "blob_storage",
			Name:      "ops_queued",
			Help:      "Number of blob storage operations waiting to be processed, partitioned by user and type.",
		},
		[]string{
			// Which user has requested the operation?
			"user",
			// Of what type is the operation?
			"type",
		},
	)
)

func init() {
	prometheus.MustRegister(opsQueued)

}

func ExampleGaugeVec() {

	// Increase a value using compact (but order-sensitive!) WithLabelValues().
	opsQueued.WithLabelValues("bob", "put").Add(4)
	// Increase a value with a map using WithLabels. More verbose, but order
	// doesn't matter anymore.
	opsQueued.With(prometheus.Labels{"type": "delete", "user": "alice"}).Inc()
}

func run() {
	http.Handle("/metrics", promhttp.Handler())
	http.ListenAndServe(":9090", nil)
}

func main() {

	run()

	ExampleGaugeVec()
}
```
Running `go run main.go`

Result: 
```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4997    0  4997    0     0   594k      0 --:--:-- --:--:-- --:--:--  609k
```

**Comment by ivanayov** [comment] 2019-10-25 14:37
One last example - when I register Gauge with Labels:
```
var (
	opsQueued = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: "our_company",
			Subsystem: "blob_storage",
			Name:      "ops_queued",
			Help:      "Number of blob storage operations waiting to be processed, partitioned by user and type.",
		},
		[]string{
			// Which user has requested the operation?
			"user",
			// Of what type is the operation?
			"type",
		},
	)
)

func init() {
	prometheus.MustRegister(opsQueued.WithLabelValues("bob", "put"))
}

func ExampleGaugeVec() {

	// Increase a value using compact (but order-sensitive!) WithLabelValues().
	opsQueued.WithLabelValues("bob", "put").Add(4)
	// Increase a value with a map using WithLabels. More verbose, but order
	// doesn't matter anymore.
	opsQueued.With(prometheus.Labels{"type": "delete", "user": "alice"}).Inc()
}

func run() {
	http.Handle("/metrics", promhttp.Handler())
	http.ListenAndServe(":9090", nil)
}

func main() {

	run()

	ExampleGaugeVec()
}
```
Running `go run main.go`

Result:
```
$ curl http://localhost:9090/metrics | grep ops_queued
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5238    0  5238    0     0   788k      0 --:--:-- --:--:-- --:--:--  852k
# HELP our_company_blob_storage_ops_queued Number of blob storage operations waiting to be processed, partitioned by user and type.
# TYPE our_company_blob_storage_ops_queued gauge
our_company_blob_storage_ops_queued{type="put",user="bob"} 0
```

**Comment by beorn7** [comment] 2019-10-25 22:06
The reason for your problem is that `http.ListenAndServe` only returns when an error happens. See https://golang.org/pkg/net/http/#ListenAndServe . In other words, the call to `ExampleGaugeVec` or `ExampleGauge` never happens.

Since this is definitely not a bug in client_golang, I close this issue now. The most suitable forum to discuss problems like this is the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users). We use GitHub issues for bugs and to track feature development. On the mailing list, more people are available to potentially respond to your problem, and the whole community can benefit from the answers provided.

**Closed by beorn7** 2019-10-25 22:06 UTC
