### ISSUE TITLE
Cut v1.0.0

### ISSUE THREAD

**Issue by breerly** [prometheus/client_golang#363] opened 2017-12-07 19:57 UTC
The last release, v0.8.0, is over a year old: to me that indicates that we should commit to the current API for the course of a v1.x major.

Instead of eventually cutting a v0.9.0 containing breaking changes, that should be considered a 2.0. This will let other v1.x libraries build off of this one, and be able to assume no breaking changes for the life of 1.x. 

* https://semver.org/
* https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by beorn7** [comment] 2017-12-11 12:38
Duplicate of #344 . See there for discussion.

**Closed by beorn7** 2017-12-11 12:38 UTC
