### ISSUE TITLE
documentation for API client

### ISSUE THREAD

**Issue by FPurchess** [prometheus/client_golang#194] opened 2016-03-09 13:36 UTC
It would be very useful to have a short example on how to perform query operations using the client (e.g. godoc examples) or, if a documentation of any form exists, reference it in the readme.

**Comment by beorn7** [comment] 2016-03-09 13:48
http://prometheus.io/docs/querying/api/ is the documentation, and it is linked from the README.md.

**Comment by beorn7** [comment] 2016-03-09 13:49
Please let us know in which way it isn't obvious enough.

**Comment by FPurchess** [comment] 2016-03-09 13:59
@beorn7 Thanks for the fast reply!

The link explains the API usage in general quite well, but does not explain how make queries using the client (https://godoc.org/github.com/prometheus/client_golang/api/prometheus). Do I miss something here?

**Comment by beorn7** [comment] 2016-03-09 14:13
Now I got it, sorry for not understanding earlier.

Yeah, this code is pretty much undocumented and arguably WIP.

I'll leave it to @fabxc to clarify.

**Comment by FPurchess** [comment] 2016-03-09 14:30
:+1: 

I assume it would look like that
``` go
import (
	"fmt"
	"golang.org/x/net/context"
	"github.com/prometheus/client_golang/api/prometheus"
)

ctx, cancel := context.WithCancel(context.Background())
defer cancel()

client, err = prometheus.New(prometheus.Config{Address:"<prometheus-url>"})
if err != nil {
	fmt.Errorf("%v", err)
}

q = prometheus.NewQueryAPI(client)

value, err := q.Query(ctx, "sum(metric)", time.Now())
if err != nil {
	fmt.Errorf("%v", err)
}

// FIXME how to get the real information out of "value" (model.Value)
```

**Comment by RomainBelorgey** [comment] 2016-08-25 14:34
Did someone know how to get the information from value in the example of @FPurchess ?
It gives me only a string and the metric's type. Is it possible to get the metric ?

**Comment by carlpett** [comment] 2016-10-18 08:40
@RomainBelorgey You need to inspect the result of `value.Type()`. I do something like this:

```go
            switch {
            case val.Type() == model.ValScalar:
                scalarVal := val.(*model.Scalar)
                // handle scalar stuff
            case val.Type() == model.ValVector:
                vectorVal := val.(model.Vector)
                for _, elem := range vectorVal {
                    // do something with each element in the vector
            // etc
```

`model` is this import: `"github.com/prometheus/common/model"`

**Comment by yinchuan** [comment] 2017-09-08 05:14
Thanks @carlpett

**Comment by beorn7** [comment] 2019-05-06 22:14
I'll re-assign this to @krasi-georgiev as @fabxc is unlikely to work in this.

@krasi-georgiev I leave it to you to vet this. Perhaps it can be closed.

**Comment by krasi-georgiev** [comment] 2019-05-07 09:13
lets keep it open in case someone decides to work on this.

**Closed** 2019-08-09 21:23 UTC
Labels: enhancement, help wanted, low hanging fruit

**Comment by notjames** [comment] 2020-06-18 01:05
Has any work been done on this? I'm having a H*LL of a time trying to dereference a matrix to debug why it seems like I'm getting more values from prometheus than I'm supposed to be getting:


```
type PromRequest struct {
	Endpoint  string   `json:"endpoint,omitempty"`
	Query     string   `json:"query:omitempty"`
	Series    []string `json:"series:omitempty"`
	TimeRange string   `json:"timerange:omitempty"`
	Step      string   `json:"step:omitempty"`
}

func getMetricsWithRange(pr *PromRequest) (model.Value, error) {
	duration, _ := time.ParseDuration(pr.TimeRange)
	step, _ := time.ParseDuration(pr.Step)
	prClient, err := api.NewClient(api.Config{Address: pr.Endpoint})
	if err != nil {
		return nil, err
	}

	v1api := v1.NewAPI(prClient)
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	r := v1.Range{
		Start: time.Now().Add(-duration),
		End:   time.Now(),
		Step:  step,
	}
	result, warnings, err := v1api.QueryRange(ctx, pr.Query, r)
	if err != nil {
		return nil, err
	}
	if len(warnings) > 0 {
		fmt.Printf("too many warnings for query: %s: %v", pr.Query, warnings)
	}

	fmt.Println("query: " + pr.Query)
        fmt.Println("data: " + ((SOMEKIND OF FREAKIN ABILITY TO JSON.MARSHAL() HERE))
	return result, nil
}

func MetricsHandler(c buffalo.Context) error {
		qd, err := getMetricsWithRange(&PromRequest{
			Endpoint:  env.Get(env.MetricsAPIEndpoint),
			Query:     c.Param("query"),
			TimeRange: c.Param("timerange"),
			Step:      c.Param("step"),
		})
		if err != nil {
			return c.Error(gateway.HTTPStatusFromCode(status.Convert(err).Code()), errors.WithStack(err))
		}

		return c.Render(http.StatusOK, r.JSON(qd))
}
```

I cannot for the life me figure out how to marshal the data. Full disclosure, I'm really a n3wb to go still and there are nuances to the language with respect to people's implementation that I just don't understand and this is one of them.

**Comment by beorn7** [comment] 2020-06-18 09:48
I don't think we are in any position here to give an introduction to Go or HTTP APIs in general (or the combination thereof, i.e. how typically HTTP APIs are handled in Go), but there is probably always room for improving the specific documentation for this library. I'm just not sure if it will help you in your position. Have you tried the various [community channels](https://prometheus.io/community/) to get help? Like the IRC channel or the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) mailing list? A Go-focused forum might also help here.

**Comment by bwplotka** [comment] 2020-06-18 17:10
Agree with @beorn7 

But I looked super quickly on your code.

What is happening probably is that you ignore error check for those things:

```
duration, _ := time.ParseDuration(pr.TimeRange)
	step, _ := time.ParseDuration(pr.Step)
```

This means that if there is any typo in those strings (which is super easy to do!), you would NOT be aware and 0 step and 0 duration would be passed. Both can potentially cause unexpected behavior of your code. Hope that helps :hugs:

**Comment by notjames** [comment] 2020-06-19 08:17
Thanks all. I think what I was seeking was understanding as to why the `values.Matrix` type doesn't have a `JSON.Marshal()` as this is the type of data I'm pulling from Prom. OTH, after doing some digging into my stack, I determined that my code is in fact returning proper data and the thing that is marshalling the data seems to be the culprit at least from a cursory perspective.

I'll take under advisement the error checking on those two functions. Thank you!
