### ISSUE TITLE
Add valueType to Desc (or create new type) 

### ISSUE THREAD

**Issue by discordianfish** [prometheus/client_golang#266] opened 2016-12-28 10:54 UTC
Hi,

for most exporters it's encouraged to use ConstMetrics. To initialize your metrics just once, you often end up preparing the Desc first for use with NewConstMetric later. Beside the Desc, you also need to specific the valueType. This means you need to keep both the desc and the value type in some data structure.

While it's not a problem to create a struct { metric: ..., valueType: } or use a map with a field for both, it seems much nicer from a UX perspective if valueType would be made part of Desc.

I'd also argue you would never use the same Desc for two different value types, since the metric name and help string should already describe what type a metric is.

@beorn7 Thoughts? Maybe this is something you already plan to do and I missed the issue?

**Comment by brian-brazil** [comment] 2016-12-28 11:00
Dupe of #222 I believe.

**Closed by brian-brazil** 2016-12-28 11:00 UTC

**Comment by discordianfish** [comment] 2016-12-28 11:11
Ah perfect, thanks!
