### ISSUE TITLE
http: superfluous response.WriteHeader

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#730] opened 2020-03-25 08:51 UTC
my code:
`http.Handle(*metricsPath, promhttp.Handler())`

logs: 
<30>2020-03-25T16:42:46.704128+08:00 cmp001 libvirt-qemu-exporter[21928]: 2020/03/25 16:42:46 http: superfluous response.WriteHeader call from libvirt-qemu-exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:58)
<30>2020-03-25T16:42:46.704923+08:00 cmp001 libvirt-qemu-exporter[21928]: 2020/03/25 16:42:46 http: superfluous response.WriteHeader call from exporter/vendor/github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:58)

**Comment by fcddk** [comment] 2020-03-25 09:15
version v1.12.1

**Comment by beorn7** [comment] 2020-03-26 14:11
>  v1.12.1

This repository currently only goes up to v1.5.1. Could you doublecheck which version you are using?

**Comment by fcddk** [comment] 2020-03-27 06:44
I'm sorry, version: 1.2.1.

**Comment by beorn7** [comment] 2020-03-27 13:56
Then this is probably a dupe of #672, fixed in v1.5.1. Please upgrade. If the problem still occurs, please follow up here, and I'll re-open.

**Closed by beorn7** 2020-03-27 13:56 UTC
