### ISSUE TITLE
duplicate metrics collector registration attempted

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#733] opened 2020-04-08 06:33 UTC
My constLabelsvalue has not been repeated, but he still reported such errors occasionally.

**Comment by fcddk** [comment] 2020-04-08 06:55
Data loss due to this reason.

**Comment by fcddk** [comment] 2020-04-08 06:58
`Desc{fqName: "mem_memfree", help: "", constLabels: {account="test-01",data_type="vm",resource_id="210024e0-1406-498e-a069-0d5261000d57",resource_name="测试勿删",vm_id="210024e0-1406-498e-a069-0d5261000d57"}, variableLabels: [service region]}}] error: duplicate metrics collector registration attempted`

**Comment by fcddk** [comment] 2020-04-08 06:59
I can guarantee that the resource_id is unique in the data, but it still occasionally has this error.

**Comment by beorn7** [comment] 2020-04-09 14:04
This could be a hash collision. Context is in https://github.com/prometheus/client_golang/issues/222 . The plan is to fix it in v2, but perhaps there is a way to fix it in v1, too. But it would be good to know if that's really the issue. Could you provide a (ideally small) set of const labels for which you see the error?

**Comment by fcddk** [comment] 2020-05-07 11:41
more logs:

2020-05-07T11:39:10Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001953",host="compute02",instanceId="0ac8f03b-63a3-4a99-accf-1c7eef3568f9",instanceName="watcher-test-10",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:10Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001938",host="compute02",instanceId="e0550ef6-8f4e-42f5-9860-f7f852eca6bb",instanceName="watcher-test-1",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:10Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001ac1",host="compute02",instanceId="4696b5ff-2962-47f2-98bd-7d96aa69494e",instanceName="sjt-test-efi-10",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001ac4",host="compute02",instanceId="c46b97c8-c5d3-4936-a25c-47475ddd8c23",instanceName="sjt-test-efi-11",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001950",host="compute02",instanceId="29b546fe-0c71-4034-b177-5d5c6228c2e8",instanceName="watcher-test-9",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001a70",host="compute02",instanceId="01b4a73f-37ab-441f-8925-dc2277edc5a4",instanceName="test",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001941",host="compute02",instanceId="35a86261-5e52-4bd5-8586-8a0ac134b867",instanceName="watcher-test-4",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-0000193e",host="compute02",instanceId="35a518aa-5570-49f5-a03a-b28522e91aef",instanceName="watcher-test-3",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001abe",host="compute02",instanceId="f0167db3-0f75-4813-8f81-415e0a59957a",instanceName="sjt-test-efi-iso",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001944",host="compute02",instanceId="76b6300d-2c71-40ab-b065-cf795de97eeb",instanceName="watcher-test-5",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001512",host="compute02",instanceId="eea1cf19-5566-4e04-aa34-da572ec261f4",instanceName="shy_test01",projectId="8fb48e67aa4d48e8882cce75d08c9c5d",projectName="shy_test",region="openstack",stateDesc="the domain is running",userId="d691aa3914d84fb5aae8ffd3406dd0f8",userName="shy_test"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001aac",host="compute02",instanceId="824a833b-359c-421c-a10a-e033dc58dc1e",instanceName="sjt-test-efi-5",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-000019ec",host="compute02",instanceId="045a660d-6ebe-4352-93a5-b7694028083d",instanceName="dfdf",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-0000193b",host="compute02",instanceId="ceb07eba-1f70-4bd5-ae20-9c09e4d2c769",instanceName="watcher-test-2",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-0000194d",host="compute02",instanceId="a059aa8b-d736-42d7-bcb4-fbe0bc8d2966",instanceName="watcher-test-8",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001947",host="compute02",instanceId="9506ee24-e9dd-4c4f-a488-2d7d094452f8",instanceName="watcher-test-6",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-0000194a",host="compute02",instanceId="50c9e16a-dbf4-4e53-b595-a0f45a777a2d",instanceName="watcher-test-7",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001953",host="compute02",instanceId="0ac8f03b-63a3-4a99-accf-1c7eef3568f9",instanceName="watcher-test-10",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001938",host="compute02",instanceId="e0550ef6-8f4e-42f5-9860-f7f852eca6bb",instanceName="watcher-test-1",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted
2020-05-07T11:39:40Z W! register a domainMetric[metric:&{ gauge [] map[] 1 Desc{fqName: "libvirt_domain_state_code", help: "Code of the domain state", constLabels: {domain="instance-00001ac1",host="compute02",instanceId="4696b5ff-2962-47f2-98bd-7d96aa69494e",instanceName="sjt-test-efi-10",projectId="0606e9bf4e9c4334b6cb9a5012c60fb8",projectName="admin",region="openstack",stateDesc="the domain is running",userId="5f0b0ff35b914c84b24efb363965530d",userName="admin"}, variableLabels: []}}] error: duplicate metrics collector registration attempted

**Comment by beorn7** [comment] 2020-05-07 12:13
If you get so many errors, I doubt it's a hash collision. That should most likely result in a single instance of duplicate registration. Less likely in two, even less likely in three, and so on. With this number of errors, it looks more like a bug in your code that accidentally tries to register everything twice.

Sadly, the error message doesn't tell us with which metrics the registration is conflicting (because they are hashed). Ideally, you could find out a pair of colliding metrics and reproduce the error message with minimal code.

**Comment by beorn7** [comment] 2020-09-09 14:08
I'll close this for lack of follow up.

The possibility of hash collisions remains a known issue tracked in #222 .

**Closed by beorn7** 2020-09-09 14:08 UTC
