### ISSUE TITLE
Implementing a metric in an http interface and tagging two sets of tags

### ISSUE THREAD

**Issue by fcddk** [prometheus/client_golang#729] opened 2020-03-25 02:13 UTC
`// Gatherers is a slice of Gatherer instances that implements the Gatherer
// interface itself. Its Gather method calls Gather on all Gatherers in the
// slice in order and returns the merged results. Errors returned from the
// Gather calls are all returned in a flattened MultiError. Duplicate and
// inconsistent Metrics are skipped (first occurrence in slice order wins) and
// reported in the returned error.
//
// Gatherers can be used to merge the Gather results from multiple
// Registries. It also provides a way to directly inject existing MetricFamily
// protobufs into the gathering by creating a custom Gatherer with a Gather
// method that simply returns the existing MetricFamily protobufs. Note that no
// registration is involved (in contrast to Collector registration), so
// obviously registration-time checks cannot happen. Any inconsistencies between
// the gathered MetricFamilies are reported as errors by the Gather method, and
// inconsistent Metrics are dropped. Invalid parts of the MetricFamilies
// (e.g. syntactically invalid metric or label names) will go undetected.
type Gatherers []Gatherer`

In this way, it is difficult to implement two sets of labels for a metric in an exporter.

**Comment by fcddk** [comment] 2020-03-25 02:14
for the logs:is invalid: duplicate label names

**Comment by beorn7** [comment] 2020-03-26 14:26
I don't quite understand the question. Could you provide an example of this failing?

Given how many exporters have been written with this library, I would assume this is more a usage question than a bug report. It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.

**Comment by beorn7** [comment] 2020-04-09 14:05
Is this related to #733 ?

**Comment by beorn7** [comment] 2020-05-18 13:40
With the lack of follow-up, I assume this is a dupe of #733. Please follow up with more details if not.

**Closed by beorn7** 2020-05-18 13:40 UTC
