### ISSUE TITLE
How to register new gauges - Migrating from InlfuxDB

### ISSUE THREAD

**Issue by prsolucoes** [prometheus/client_golang#169] opened 2015-08-26 19:43 UTC
Hi,

We are migrating from influxdb + grafana to prometheus + grafana. But we have a problem on our Go scripts to expose/send our data to prometheus.

What i need:

```
Metric: Server memory (server-memory)
    [
    Label: server   Value: "vps001"
    Label: free   Value: 123
    ]
    
    [
    Label: server   Value: "vps001"
    Label: total   Value: 500
    ]
    
    [
    Label: server   Value: "vps001"
    Label: used   Value: 12
    ]
```

But i dont know how to do it with go client. My current code is:

``` go
{
    memoryGauge := prometheus.NewGauge(prometheus.GaugeOpts{
        Namespace: "prsolucoes",
        Name: "server_memory",
        Help: "Free memory of server",
        ConstLabels: prometheus.Labels{"type": "free"},
    })

    prometheus.MustRegister(memoryGauge)
    memoryGauge.Set(float64(v.Free));
}
{
    memoryGauge := prometheus.NewGauge(prometheus.GaugeOpts{
        Namespace: "prsolucoes",
        Name: "server_memory",
        Help: "Used memory of server",
        ConstLabels: prometheus.Labels{"type": "used"},
    })

    prometheus.MustRegister(memoryGauge)
    memoryGauge.Set(float64(v.Used));
}
{
    memoryGauge := prometheus.NewGauge(prometheus.GaugeOpts{
        Namespace: "prsolucoes",
        Name: "server_memory",
        Help: "Total memory of server",
        ConstLabels: prometheus.Labels{"type": "total"},
    })

    prometheus.MustRegister(memoryGauge)
    memoryGauge.Set(float64(v.Total));
}
```

It is not a bug, but after lost my day searching and not found the answer, i prefer post here.

**Comment by brian-brazil** [comment] 2015-08-26 19:50
What you probably want is https://github.com/prometheus/node_exporter (presuming you're on unix)

**Comment by prsolucoes** [comment] 2015-08-27 02:32
Olá Brian,

Tem alguma forma de contato, tipo skype, para que eu possa falar com você? Por aqui vamos demorar muito até nos entender.

I tried it:

``` go
memoryGauge = prometheus.NewGauge(prometheus.GaugeOpts{
    Namespace: "prsolucoes",
    Name: "server_memory",
    Help: "Memory of server",
    ConstLabels: prometheus.Labels{"type": "free"},
})

memoryGauge.WithLabelValues("type", "free").Observe(float64(v.Free))
memoryGauge.WithLabelValues("type", "used").Observe(float64(v.Used))
memoryGauge.WithLabelValues("type", "total").Observe(float64(v.Total))
```

Thanks.

**Comment by brian-brazil** [comment] 2015-08-27 11:48
I don't speak Portuguese I'm afraid.

The problem with your first example is that the help strings are different, which the runtime error message should have told you.

There's several problems with your second example, what you want is
```
memoryGauge := prometheus.NewGaugeVec(prometheus.GaugeOpts{
    Namespace:   "prsolucoes",
    Name:        "server_memory",
    Help:        "Memory of server",
  }, []string{"type"})

  prometheus.MustRegister(memoryGauge)

  memoryGauge.WithLabelValues("free").Set(float64(1))
  memoryGauge.WithLabelValues("used").Set(float64(2))
  memoryGauge.WithLabelValues("total").Set(float64(3))
```

Putting this data in one metric is discouraged, as is using `type` as a label name. We also recommend putting the units in the metrics name.

**Comment by beorn7** [comment] 2015-09-01 22:07
Closing this as it is not a bug or feature request.

Getting support from the community probably works much better on the mailing list.

**Closed by beorn7** 2015-09-01 22:07 UTC
